"""empty message

Revision ID: 6315334d98ea
Revises: 
Create Date: 2020-06-11 15:41:54.855124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6315334d98ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('secret_key', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_secret_key'), 'user', ['secret_key'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('(uuid_generate_v4())'), nullable=False),
    sa.Column('game_id', sa.String(length=12), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_game_id'), 'game', ['game_id'], unique=True)
    op.create_index(op.f('ix_game_owner'), 'game', ['owner'], unique=False)
    op.create_table('score',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('(uuid_generate_v4())'), nullable=False),
    sa.Column('game', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_game'), 'score', ['game'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_game'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_game_owner'), table_name='game')
    op.drop_index(op.f('ix_game_game_id'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_secret_key'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
